name: ChatFilter
version: '1.0'
main: com.lavasr.ChatFilter
api-version: '1.21'
author: 403Denied

permissions:
  filter.add:
    description: Allows the user to add words to the filter.
    default: op
  filter.remove:
    description: Allows the user to remove words from the filter.
    default: op
  filter.list:
    description: Allows the user to list all filtered words.
    default: op
  filter.reload:
    description: Allows the user to reload the filter configuration.
    default: op
  filter.use:
    description: Allows the user the basic filter management command
    default: op
  filter.notify:
    description: Allows the user to receive notifications about filtered messages.
    default: true
  filter.check:
    description: Allows the user to checked if a string would be caught by the filter.
    default: true